ALTER TABLE ak_users
  DROP COLUMN IS_ADMIN;
ALTER TABLE ak_users
  ADD PICTURE_PATH VARCHAR(255);
ALTER TABLE ak_users
  MODIFY PICTURE LONGBLOB;

CREATE TABLE AK_VISITORS (
  ID              BIGINT(20)   NOT NULL    AUTO_INCREMENT PRIMARY KEY,
  FB_ID           VARCHAR(50)  NOT NULL,
  FIRST_NAME      VARCHAR(250) NOT NULL    DEFAULT '',
  LAST_NAME       VARCHAR(250) NOT NULL    DEFAULT '',
  EMAIL           VARCHAR(100)             DEFAULT '',
  USER_STATUS     INT(11)      NOT NULL    DEFAULT 1,
  INSERTION_DATE  DATETIME,
  LAST_LOGIN_DATE DATETIME
);

INSERT INTO AK_SETTINGS (SKEY, SVALUE) VALUES ('blog.enabled', 'off');
INSERT INTO AK_SETTINGS (SKEY, SVALUE) VALUES ('blog.style', 'grid');
INSERT INTO AK_SETTINGS (SKEY, SVALUE)
VALUES ('email.addresses', 'pkasfiki@gmail.com;info@fitnesshousebypenny.gr;natsaros@hotmial.com');